order_descriptions = {
    'cols': {
        'partner': ('Партнер', 'Партнёр'),
        'receiver_name': ('Имя получателя', 'ФИО', 'ФИО получателя'),
        'receiver_phone_number': ('Номер получателя', 'Номер телефона'),
        'pan': ('Номер карты',),
        'shipment_point': ('Адрес вывоза',),
        'delivery_point': ('Адрес доставки',),
        'receiver_iin': ('ИИН получателя', 'ИИН'),
        'item': ('Продукт',),
        'delivery_datetime': ('Дата доставки', 'Доставить до'),
        'country': ('Страна', 'Страна доставки'),
        'city': ('Город', 'Город доставки'),
        'comment': ('Комментарий',),
        'manager': ('Менеджер', 'Канал'),
        'idn': ('IDN карты',),
        'id': ('ID', 'ID заявки'),
        'created_at': ('Дата создания',),
        'partner_order_id': ('ID заявки партнера',),
        'type': ('Тип',),
        'actual_delivery_datetime': ('Фактическая дата доставки',),
        'area': ('Зона доставки',),
        'courier': ('Курьер',),
        'status': ('Статус',),
        'history': ('История заявок',),
        'postcontrol_creator_name': ('Coздавший последконтроль',),
        'postcontrol_approver_name': ('Принявший последконтроль',),
        'status_comment': ('Комментарии',),
        'current_status_name': ('Текущий статус',),
        'current_status_datetime': ('Дата текущего статуса',),
        'initial_delivery_datetime': ('Исходная дата доставки',),
        'courier_appointed_at': ('Дата назначения курьера',),
    },
}

delivery_status_description = {
    'statuses': {
        'На пути к пункту вызова': 'on-the-way-to-call-point',
        'Отложен': 'postponed',
        'Недозвон': 'noncall',
        'Отменен': 'cancelled',
        'being_finalized': 'being_finalized',
        'Видео проверка пройдена': 'video_check_passed',
        'Видео недоступно': 'video_unavailable',
        'Видео постконтроль': 'video_postcontrol',
        'video_postcontrol_being_finalized': 'video_postcontrol_being_finalized',
        'Проверка видео не удалась': 'video_check_failed',
        'Смс постконтроль': 'sms_postcontrol',
        'sms_postcontrol': 'sms_postcontrol_being_finalized',
        'Смс недоступно': 'sms_unavailable',
        'Смс не удалось': 'sms_failed',
        'Доставлен': 'is_delivered',
        'Cброшен': 'is_reset'
    },
}
