from tortoise.contrib.postgres.json_functions import operator_keywords

from .utils import _postgres_json_in

operator_keywords["in"] = _postgres_json_in
from .android import(
    AndroidVersion,
    get_last_android_version,
)
from .area import(
    Area,
    AreaCannotBeArchived,
    area_activate,
    area_archive,
    area_create,
    area_delete,
    area_get,
    area_get_list,
    area_update,
)
from .category import(
    Category,
    category_create,
    category_delete,
    category_delete_bulk,
    category_get,
    category_get_list,
    category_update,
)
from .country import(
    Country,
    country_create,
    country_delete,
    country_get,
    country_get_list,
    country_update,
)
from .deliverygraph import(
    DeliveryGraph,
    deliverygraph_create,
    deliverygraph_delete,
    deliverygraph_get,
    deliverygraph_get_list,
    deliverygraph_list_default,
    deliverygraph_update,
)
from .direction import direction_get
from .emails import Email
from .external_service_history import(
    ExternalServiceHistory,
    ExternalServiceHistoryDoesNotExist,
    ExternalServiceHistoryError,
    external_service_history_create,
    external_service_history_get,
    external_service_history_get_list,
)
from .feedback import(
    Feedback,
    FeedbackAlreadyExist,
    FeedbackNotFound,
    FeedbackReason,
    FeedbackReasonNotFound,
    feedback_create,
    feedback_delete,
    feedback_get,
    feedback_list,
    feedback_reason_create,
    feedback_reason_delete,
    feedback_reason_get_list,
    feedback_reason_update,
    feedback_update_status,
)
from .group import(
    Group,
    GroupAlreadyExists,
    GroupNotFound,
    group_create,
    group_get,
    group_list,
    group_permission_add,
    group_permission_remove,
    group_user_add,
    group_user_remove,
)
from .history import(
    History,
    HistoryCreationError,
    history_create,
    history_get_list,
)
from .invited_user import(
    InvitedUser,
    InvitedUserEntityError,
    InvitedUserNotFound,
    invited_user_create,
    invited_user_get,
)
from .item import(
    CityAlreadyInItem,
    Item,
    ItemCannotBeDeleted,
    ItemCommonError,
    ItemPostControlCheckFailure,
    ItemNotFound,
    item_cities_add,
    item_create,
    item_delete,
    item_delete_bulk,
    item_get,
    item_get_list,
    item_update,
    itemshipmentpoints_create,
)
from .order import(
    OrderAlreadyExists,
    DistanceMatrixError,
    InvalidPointCoords,
    NotDistributionCouriersError,
    NotDistributionOrdersError,
    Order,
    OrderAddress,
    OrderAddressNotFound,
    OrderAlreadyDelivered,
    OrderAlreadyHaveCourierError,
    OrderEntitiesError,
    OrderIsNotSubjectToPostControl,
    OrderNotFound,
    OrderPostControlMaximumNumberLimitExceeded,
    OrderPostponeError,
    OrderReceiverIINNotProvided,
    OrderSmsCheckError,
    OrderSmsMaximumLimitExceeded,
    OrderGeolocation,
    OrderStatuses,
    StatusAfterError,
    StatusAlreadyCurrent,
    check_is_delivery_points_in_polygon,
    external_order_create,
    external_order_create_v2,
    get_external_order,
    order_address_get_list,
    order_address_update,
    order_address_update_v2,
    order_average_time_deviation,
    order_biometry_verify,
    order_cancel_at_client,
    order_change_status,
    order_courier_assign,
    order_create,
    order_create_v2,
    order_delivered_today,
    order_distribution_for_area,
    order_distribution_selective,
    order_ensure_exists,
    order_get,
    order_get_couriers_current_executable_orders,
    order_get_current_status,
    order_get_list,
    order_get_list_v2,
    order_get_list_mobile,
    order_get_v1,
    order_get_v2,
    order_import_from_excel,
    order_import_get_sample,
    order_import_history,
    order_mass_courier_assign,
    order_mass_status_update,
    order_pan,
    order_pan_v2,
    order_report,
    order_reschedule,
    order_restore,
    order_cancel,
    order_expel_courier,
    order_postpone,
    order_noncall,
    order_resume,
    order_sms_postcontrol,
    order_sms_postcontrol_check,
    get_order_for_order_sms_postcontrol_check,
    order_send_notification_to_client_on_currier_assign,
    order_update,
    order_update_delivery_status_on_status_change,
    order_update_status,
    order_revise,
    order_finalize_at_cs,
    orders_get_count,
    order_statuses_get_count,
    order_status_bulk_update,
)
from .comment import (
    Comment,
    CommentImage,
)
from .partner import(
    Partner,
    PanValidationMask,
    PartnerCity,
    PartnerActionException,
    PartnerAlreadyExists,
    PartnerNotFound,
    PartnersCanNotBeDeleted,
    delivery_service_create,
    partner_create,
    partner_delete,
    partner_delete_bulk,
    partner_ensure_exists,
    partner_get,
    partner_get_list,
    partner_get_many,
    partner_update,
    get_partner_cities,
    get_partner_countries,
)
from .permission import(
    Permission,
    permission_create,
    permission_get,
    permission_get_or_404,
    permission_list
)
from .place import(
    Place,
    PlaceNotFound,
    place_create,
    place_delete,
    place_get,
    place_get_list,
    place_update,
)
from .postcontrol import(
    CanNotCompleteOrder,
    PAN,
    PostControl,
    PostControlConfig,
    PostControlCanNotDelete,
    PostControlIsNotSubjectToChange,
    PostControlIsNotSubjectToDelete,
    SMSPostControl,
    postcontrol_accept,
    postcontrol_create,
    postcontrol_decline,
    postcontrol_delete,
    postcontrol_get,
    postcontrol_get_list,
    postcontrol_make_resolution,
)
from .profile import(
    ProfileAlreadyExists,
    ProfileBranchManager,
    ProfileCourier,
    ProfileDispatcher,
    ProfileManager,
    ProfileBankManager,
    ProfileNotFound,
    ProfileOwner,
    ProfilePartnerBranchManager,
    ProfileServiceManager,
    ProfileSorter,
    ProfileSupervisor,
    ProfileLogist,
    ProfileCallCenterManager,
    ProfileGeneralCallCenterManager,
    ProfileSupport,
    StatusAlreadySet,
    courier_list,
    courier_stats,
    courier_stats_get,
    courier_end_work,
    courier_start_work,
    get_all_user_profiles,
    new_profile_create,
    profile_biometry_verify,
    profile_delete,
    profile_get,
    profile_get_by_id,
    profile_get_by_profile_type,
    profile_get_list,
    profile_get_multiple,
    profile_status_update,
    profile_types_to_models,
    profile_update_by_profile_id,
    profile_update_by_user_id,
    profile_send_magic_link,
)
from .public_api_token import(
    PublicApiToken,
    PublicApiTokenAlreadyExists,
    PublicApiTokenNotFound,
    public_api_token_create,
    public_api_token_get
)
from .rate import(
    Rate,
    rate_list,
)
from .statistics import(
    CourierStat,
    courier_progress_get,
    courier_stat_get,
    statistics_get,
    statistics_get_by_date,
    statistics_get_by_hour,
    statistics_heatmap_get_by_date,
)
from .status import(
    Status,
    StatusInOtherDependings,
    status_create,
    status_delete,
    status_get,
    status_get_list,
    status_update,
)
from .token import(
    RevokedToken,
    token_get,
    token_revoke,
)
from .transport import(
    Transport,
    TransportNotFound,
    transport_create,
    transport_delete,
    transport_get,
    transport_update,
)
from .user import(
    User,
    UserAlreadyExists,
    UserNotFound,
    get_user_profile_with_info,
    user_change_photo,
    user_get_by_email,
    user_create,
    user_delete,
    user_get,
    user_get_by_phone_number,
    user_get_list,
    user_get_multiple_profiles,
    user_get_object_or_404,
    user_permission_add,
    user_permission_remove,
    user_set_password,
    user_set_password_v2,
    user_update,
)
from .fields.file import FileValidationError
from .product import Product
from .courier_service_status import CourierServiceStatus
from .courier_service import CourierService


class EntityDoesNotExist(Exception):
    """Generic exception. Raises if entity with provided ID does not exist."""
