-- upgrade --
CREATE TABLE IF NOT EXISTS "country" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "region" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    "country_id" INT REFERENCES "country" ("id") ON DELETE SET NULL
);
COMMENT ON TABLE "region" IS 'Region equal to Oblast in Kazakhstan';
CREATE TABLE IF NOT EXISTS "city" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "region_id" INT REFERENCES "region" ("id") ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "area" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "slug" VARCHAR(255),
    "scope" JSONB NOT NULL,
    "city_id" INT NOT NULL REFERENCES "city" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "place" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "address" VARCHAR(255) NOT NULL,
    "latitude" DECIMAL(10,8) NOT NULL,
    "longitude" DECIMAL(11,8) NOT NULL,
    "city_id" INT REFERENCES "city" ("id") ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "upload" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "uuid" UUID NOT NULL,
    "content" BYTEA NOT NULL,
    "mime_type" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "type" VARCHAR(9) NOT NULL
);
COMMENT ON COLUMN "upload"."type" IS 'USER: user, ITEM: item, ORDER: order, TRANSPORT: transport, PARTNER: partner';
CREATE TABLE IF NOT EXISTS "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "phone_number" VARCHAR(12) NOT NULL UNIQUE,
    "first_name" VARCHAR(32),
    "last_name" VARCHAR(32),
    "middle_name" VARCHAR(32),
    "iin" VARCHAR(12)  UNIQUE,
    "credentials" JSONB,
    "is_active" BOOL NOT NULL  DEFAULT True
);
CREATE INDEX IF NOT EXISTS "idx_user_first_n_2d121b" ON "user" ("first_name");
CREATE INDEX IF NOT EXISTS "idx_user_last_na_3c4ee3" ON "user" ("last_name");
CREATE INDEX IF NOT EXISTS "idx_user_middle__cd8ff5" ON "user" ("middle_name");
CREATE INDEX IF NOT EXISTS "idx_user_iin_12f077" ON "user" ("iin");
CREATE TABLE IF NOT EXISTS "access_token" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "token" VARCHAR(255) NOT NULL UNIQUE,
    "token_type" TEXT NOT NULL,
    "is_revoked" BOOL NOT NULL  DEFAULT True,
    "issued_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" TIMESTAMPTZ,
    "client_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "profile_courier" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "category" VARCHAR(1) NOT NULL  DEFAULT 'D',
    "at_work" BOOL,
    "experience_years" INT,
    "experience_months" INT,
    "start_work_hour" VARCHAR(5),
    "end_work_hour" VARCHAR(5),
    "schedule" varchar[],
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "is_identified" BOOL NOT NULL  DEFAULT False,
    "is_biometry_verificated" BOOL NOT NULL  DEFAULT False,
    "iban" VARCHAR(34),
    "item_type" VARCHAR(8),
    "transport_type" VARCHAR(10),
    "city_id" INT REFERENCES "city" ("id") ON DELETE SET NULL,
    "user_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
COMMENT ON COLUMN "profile_courier"."category" IS 'A: A, B: B, C: C, D: D';
COMMENT ON COLUMN "profile_courier"."item_type" IS 'FOOD: food, COMMON: common, DOCUMENT: document';
COMMENT ON COLUMN "profile_courier"."transport_type" IS 'CAR: car, TRUCK: truck, PICKUP: pickup, BICYCLE: bicycle, MOTORCYCLE: motorcycle, FOOT: foot';
CREATE TABLE IF NOT EXISTS "profile_manager" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "user_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "profile_owner" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "user_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "profile_service_manager" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "user_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "partner" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name_kz" VARCHAR(64) NULL UNIQUE,
    "name_ru" VARCHAR(255) NULL UNIQUE,
    "name_en" VARCHAR(255)  UNIQUE,
    "activity_name_ru" VARCHAR(255) NOT NULL,
    "address" VARCHAR(255) NULL,
    "affiliated" BOOL NOT NULL,
    "article" VARCHAR(64) NULL,
    "bin" VARCHAR(12) NULL UNIQUE,
    "is_commerce" BOOL NOT NULL,
    "leader_data" JSONB NULL,
    "consent_confirmed" BOOL NULL,
    "is_government" BOOL NULL,
    "is_international" BOOL NULL,
    "email" VARCHAR(100) NULL UNIQUE,
    "registration_date" TIMESTAMPTZ NOT NULL,
    "liq_date" DATE NULL,
    "liq_decision_date" DATE NULL,
    "credentials" JSONB NULL,
    "courier_partner_id" INT REFERENCES "partner" ("id") ON DELETE SET NULL,
    "leader_id" INT REFERENCES "profile_owner" ("id") ON DELETE SET NULL,
    "manager_id" INT REFERENCES "profile_service_manager" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "deliverygraph" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "graph" JSONB NOT NULL,
    "partner_id" INT REFERENCES "partner" ("id") ON DELETE CASCADE,
    CONSTRAINT "uid_deliverygra_graph_63d14a" UNIQUE ("graph", "partner_id")
);
CREATE TABLE IF NOT EXISTS "itemcategory" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    "item_type" VARCHAR(8) NOT NULL,
    "partner_id" INT REFERENCES "partner" ("id") ON DELETE SET NULL
);
COMMENT ON COLUMN "itemcategory"."item_type" IS 'FOOD: food, COMMON: common, DOCUMENT: document';
CREATE TABLE IF NOT EXISTS "item" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "item_type" VARCHAR(8) NOT NULL,
    "delivery_time" VARCHAR(5) NOT NULL,
    "courier_category" VARCHAR(1) NOT NULL,
    "transports" varchar[] NOT NULL,
    "post_control" BOOL NOT NULL  DEFAULT False,
    "delivery_type" VARCHAR(9),
    "deliverygraph_id" INT REFERENCES "deliverygraph" ("id") ON DELETE SET NULL,
    "itemcategory_id" INT REFERENCES "itemcategory" ("id") ON DELETE SET NULL,
    "partner_id" INT REFERENCES "partner" ("id") ON DELETE SET NULL,
    "upload_id" INT REFERENCES "upload" ("id") ON DELETE SET NULL
);
COMMENT ON COLUMN "item"."item_type" IS 'FOOD: food, COMMON: common, DOCUMENT: document';
COMMENT ON COLUMN "item"."courier_category" IS 'A: A, B: B, C: C, D: D';
COMMENT ON COLUMN "item"."delivery_type" IS 'URGENT: urgent, OPERATIVE: operative, PLANNED: planned';
CREATE TABLE IF NOT EXISTS "order" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "type" VARCHAR(9) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "delivery_datetime" TIMESTAMPTZ NOT NULL,
    "delivery_status" VARCHAR(24),
    "receiver_name" VARCHAR(255) NOT NULL,
    "receiver_iin" VARCHAR(12) NOT NULL,
    "receiver_phone_number" VARCHAR(255) NOT NULL,
    "comment" VARCHAR(255),
    "is_shown" BOOL NOT NULL  DEFAULT False,
    "city_id" INT REFERENCES "city" ("id") ON DELETE SET NULL,
    "courier_id" INT REFERENCES "profile_courier" ("id") ON DELETE SET NULL,
    "item_id" INT NOT NULL REFERENCES "item" ("id") ON DELETE CASCADE,
    "partner_id" INT NOT NULL REFERENCES "partner" ("id") ON DELETE RESTRICT
);
COMMENT ON COLUMN "order"."type" IS 'URGENT: urgent, OPERATIVE: operative, PLANNED: planned';
COMMENT ON COLUMN "order"."delivery_status" IS 'ON_THE_WAY_TO_CALL_POINT: on-the-way-to-call-point, POSTPONED: postponed, NONCALL: noncall, CANCELLED: cancelled, IS_DELIVERED: is_delivered';
CREATE TABLE IF NOT EXISTS "order.addresses" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "position" SMALLINT NOT NULL  DEFAULT 1,
    "type" VARCHAR(14) NOT NULL  DEFAULT 'delivery_point',
    "order_id" INT NOT NULL REFERENCES "order" ("id") ON DELETE CASCADE,
    "place_id" INT NOT NULL REFERENCES "place" ("id") ON DELETE CASCADE
);
COMMENT ON COLUMN "order.addresses"."type" IS 'SHIPMENT_POINT: shipment_point, DELIVERY_POINT: delivery_point';
CREATE TABLE IF NOT EXISTS "partner.addresses" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" VARCHAR(50),
    "partner_id" INT NOT NULL REFERENCES "partner" ("id") ON DELETE CASCADE,
    "place_id" INT NOT NULL REFERENCES "place" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "refresh_token" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "token" VARCHAR(255) NOT NULL,
    "token_type" TEXT NOT NULL,
    "is_revoked" BOOL NOT NULL  DEFAULT True,
    "issued_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" TIMESTAMPTZ,
    "client_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "idx_refresh_tok_client__895f9b" ON "refresh_token" ("client_id");
CREATE TABLE IF NOT EXISTS "status" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "icon" VARCHAR(50) NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "is_optional" BOOL NOT NULL  DEFAULT False,
    "after" JSONB,
    "partner_id" INT REFERENCES "partner" ("id") ON DELETE CASCADE,
    CONSTRAINT "uid_status_name_b67da9" UNIQUE ("name", "partner_id")
);
CREATE TABLE IF NOT EXISTS "order.statuses" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "order_id" INT NOT NULL REFERENCES "order" ("id") ON DELETE CASCADE,
    "status_id" INT NOT NULL REFERENCES "status" ("id") ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "transport" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "type" VARCHAR(10) NOT NULL,
    "name" VARCHAR(64) NOT NULL,
    "plate_number" VARCHAR(32),
    "fuel_consumption" DOUBLE PRECISION,
    "average_speed" INT,
    "payload" DOUBLE PRECISION,
    "width" DOUBLE PRECISION,
    "height" DOUBLE PRECISION,
    "depth" DOUBLE PRECISION,
    "capacity" DOUBLE PRECISION,
    "courier_id" INT REFERENCES "profile_courier" ("id") ON DELETE SET NULL
);
COMMENT ON COLUMN "transport"."type" IS 'CAR: car, TRUCK: truck, PICKUP: pickup, BICYCLE: bicycle, MOTORCYCLE: motorcycle, FOOT: foot';
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSONB NOT NULL
);
