-- upgrade --
ALTER TABLE "item_cities" RENAME TO "item_city";
ALTER TABLE "item_city" DROP COLUMN "id";
-- downgrade --
ALTER TABLE "item_city" RENAME TO "item_cities";
ALTER TABLE "item_cities" ADD COLUMN "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;
