-- upgrade --
DROP TABLE IF EXISTS "access_token";
DROP TABLE IF EXISTS "refresh_token";
-- downgrade --
CREATE TABLE refresh_token
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    token      VARCHAR(4080)        NOT NULL,
    token_type TEXT                 NOT NULL,
    is_revoked BOOLEAN DEFAULT TRUE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    client_id  INTEGER              NOT NULL references "user"
            ON DELETE CASCADE
);
CREATE TABLE access_token
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    token      VARCHAR(4080)         NOT NULL
        UNIQUE,
    token_type TEXT                  NOT NULL,
    client_id  INTEGER               NOT NULL
        CONSTRAINT fk_access_t_user_814154ca
            REFERENCES "user"
            ON DELETE CASCADE,
    archived   BOOLEAN DEFAULT FALSE NOT NULL
);
