-- upgrade --
CREATE TABLE IF NOT EXISTS "postcontrol_configs"
(
    "id"               INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name"             VARCHAR(255)                         NOT NULL,
    "send"             BOOLEAN DEFAULT FALSE,
    "item_id"          INT REFERENCES "item" ("id") ON DELETE CASCADE,
    "parent_config_id" INT REFERENCES "postcontrol_configs" ("id") ON DELETE CASCADE,
    CHECK ("item_id" IS NOT NULL OR "parent_config_id" IS NOT NULL)
);
CREATE UNIQUE INDEX "postcontrol_configs_u_together_item_id_name_partner_config_id" ON "postcontrol_configs" ("item_id", "name", "parent_config_id") WHERE "item_id" IS NOT NULL AND "parent_config_id" IS NOT NULL;
CREATE UNIQUE INDEX "postcontrol_configs_unique_together_name_parent_config_id" ON "postcontrol_configs" ("name", "parent_config_id") WHERE "item_id" IS NULL AND "parent_config_id" IS NOT NULL;
CREATE UNIQUE INDEX "postcontrol_configs_unique_together_item_id_name" ON "postcontrol_configs" ("item_id", "name") WHERE "item_id" IS NOT NULL AND "parent_config_id" IS NULL;
-- downgrade --
DROP TABLE IF EXISTS "postcontrol_configs";
