-- upgrade --
CREATE TABLE IF NOT EXISTS "order_geolocations" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "at_client_point" DECIMAL(11,8)[2],
    "code_sent_point" DECIMAL(11,8)[2],
    "order_id" INT  UNIQUE REFERENCES "order" ("id") ON DELETE CASCADE
);
-- downgrade --
DROP TABLE IF EXISTS "order_geolocations";
