-- upgrade --
ALTER TABLE "order" ADD "shipment_point_id" INT;
ALTER TABLE "order" ADD "delivery_point_id" INT;
CREATE TABLE IF NOT EXISTS "delivery_point" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "address" VARCHAR(255) NOT NULL,
    "latitude" DECIMAL(10,8),
    "longitude" DECIMAL(11,8)
);;
ALTER TABLE "order" ADD CONSTRAINT "fk_order_delivery_fe0b52d2" FOREIGN KEY ("delivery_point_id") REFERENCES "delivery_point" ("id") ON DELETE RESTRICT;
ALTER TABLE "order" ADD CONSTRAINT "fk_order_partner__7fcee623" FOREIGN KEY ("shipment_point_id") REFERENCES "partner_shipment_point" ("id") ON DELETE SET NULL;
-- downgrade --
ALTER TABLE "order" DROP CONSTRAINT "fk_order_partner__7fcee623";
ALTER TABLE "order" DROP CONSTRAINT "fk_order_delivery_fe0b52d2";
ALTER TABLE "order" DROP COLUMN "shipment_point_id";
ALTER TABLE "order" DROP COLUMN "delivery_point_id";
DROP TABLE IF EXISTS "delivery_point";
