-- upgrade --
ALTER TABLE "city" DROP CONSTRAINT "city_region_id_fkey";
ALTER TABLE "city" DROP COLUMN "region_id";
DROP TABLE IF EXISTS "region";
-- downgrade --
CREATE TABLE IF NOT EXISTS "region"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name"       VARCHAR(255)                         NOT NULL UNIQUE,
    "country_id" INT                                  REFERENCES "country" ("id") ON DELETE SET NULL
);
INSERT INTO "region" ("id", "name", "country_id")
SELECT 1, 'KZ', "id"
from "country"
where name ilike '%казахстан'
limit 1;
INSERT INTO "region" ("id", "name", "country_id")
SELECT 2, 'RU', "id"
from "country"
where name ilike '%россия'
limit 1;
INSERT INTO "region" ("id", "name", "country_id")
SELECT 3, 'UZ', "id"
from "country"
where name ilike '%узбекистан'
limit 1;
INSERT INTO "country" ("id", "name") values (10, 'placeholder') ON CONFLICT DO NOTHING;
INSERT INTO "region" ("id", "name", "country_id") values (4, 'placeholder', 10) ON CONFLICT DO NOTHING;
ALTER TABLE "city" ADD "region_id" INT;
UPDATE "city"
SET region_id=1
WHERE name in (
               'Алматы',
               'Астана',
               'Караганда',
               'Кокшетау',
               'Шымкент',
               'Актау',
               'Атырау',
               'Актобе',
               'Усть-Каменогорск',
               'Кызылорда',
               'Костанай',
               'Павлодар',
               'Семей',
               'Талдыкорган',
               'Тараз',
               'Уральск',
               'Экибастуз',
               'Петропавловск',
               'Уштобе'
    );
UPDATE "city"
SET region_id=2
WHERE name in (
               'Москва',
               'Санкт-Петербург',
               'Краснодар',
               'Волгоград',
               'Воронеж',
               'Красноярск',
               'Пермь',
               'Уфа',
               'Ростов-на-Дону',
               'Новосибирск',
               'Екатеринбург',
               'Казань',
               'Нижний Новгород',
               'Челябинск',
               'Самара',
               'Омск',
               'Сочи',
               'Иркутск',
               'Владивосток',
               'Калининград',
               'Рязань',
               'Тюмень',
               'Ярославль',
               'Тольятти',
               'Красногорск',
               'Ижевск',
               'Одинцово',
               'Ставрополь',
               'Сургут',
               'Томск',
               'Химки',
               'Астрахань',
               'Саратов',
               'Череповец',
               'Кемерово',
               'Архангельск',
               'Хабаровск',
               'Барнаул',
               'Набережные Челны',
               'Белгород',
               'Балашиха',
               'Тверь',
               'Чебоксары',
               'Пенза',
               'Тула',
               'Владимир',
               'Мурманск',
               'Ульяновск',
               'Курск',
               'Люберцы',
               'Оренбург',
               'Мытищи',
               'Липецк',
               'Новокузнецк',
               'Южно-Сахалинск',
               'Киров',
               'Иваново',
               'Йошкар-Ола',
               'Саранск',
               'Новороссийск',
               'Видное',
               'Реутов',
               'Королёв',
               'Подольск',
               'Тамань',
               'Братск',
               'Чита',
               'Таганрог',
               'Калуга',
               'Вологда',
               'Находка',
               'Благовещенск',
               'Пятигорск',
               'Черкесск'
    );
UPDATE "city"
SET region_id=3
WHERE name in (
    'Ташкент',
'Фергана',
'Нукус',
'Самарканд'
    );
UPDATE "city" SET "region_id"=4 WHERE "region_id" IS NULL;
ALTER TABLE "city" ALTER COLUMN "region_id" SET NOT NULL;
ALTER TABLE "city" ADD CONSTRAINT "city_region_id_fkey" FOREIGN KEY ("region_id") REFERENCES "region" ("id") ON DELETE RESTRICT;
