-- upgrade --
ALTER TABLE "item" ADD COLUMN "upload_from_gallery" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "item" DROP CONSTRAINT "item_upload_id_fkey";
ALTER TABLE "item" DROP COLUMN "upload_id";
DROP TABLE IF EXISTS "upload";
-- downgrade --
ALTER TABLE "item" ADD "upload_id" INT;
CREATE TABLE IF NOT EXISTS "upload" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "uuid" UUID NOT NULL,
    "content" BYTEA NOT NULL,
    "mime_type" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "type" VARCHAR(9) NOT NULL
);
ALTER TABLE "item" ADD CONSTRAINT "item_upload_id_fkey" FOREIGN KEY ("upload_id") REFERENCES "upload" ("id") ON DELETE SET NULL;
ALTER TABLE "item" DROP COLUMN IF EXISTS "upload_from_gallery";
