-- upgrade --
ALTER TABLE "groups" ADD "name" VARCHAR(255)  UNIQUE;
UPDATE "groups" SET "name"='Курьер' WHERE "slug"='courier';
UPDATE "groups" SET "name"='Менеджер партнера' WHERE "slug"='manager';
UPDATE "groups" SET "name"='Менеджер филиала' WHERE "slug"='branch_manager';
UPDATE "groups" SET "name"='Диспетчер' WHERE "slug"='dispatcher';
UPDATE "groups" SET "name"='Владелец' WHERE "slug"='owner';
UPDATE "groups" SET "name"='Менеджер' WHERE "slug"='service_manager';
UPDATE "groups" SET "name"='Менеджер филиала партнера' WHERE "slug"='partner_branch_manager';
UPDATE "groups" SET "name"='Сортировщик' WHERE "slug"='sorter';
UPDATE "groups" SET "name"='Менеджер банка' WHERE "slug"='bank_manager';
UPDATE "groups" SET "name"='Супервайзер' WHERE "slug"='supervisor';
UPDATE "groups" SET "name"='Логист' WHERE "slug"='logist';
UPDATE "groups" SET "name"='Менеджер колл-центра' WHERE "slug"='call_center_manager';
UPDATE "groups" SET "name"='Менеджер колл-центра (расширенный)' WHERE "slug"='general_call_center_manager';
UPDATE "groups" SET "name"='Поддержка' WHERE "slug"='support';
CREATE TABLE IF NOT EXISTS "order_comment" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "user_name" VARCHAR(255) NOT NULL,
    "text" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "order_id" INT NOT NULL REFERENCES "order" ("id") ON DELETE CASCADE,
    "user_id" INT REFERENCES "user" ("id") ON DELETE SET NULL,
    "user_role_id" VARCHAR(40) NOT NULL REFERENCES "groups" ("slug") ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "order_comment_image" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "image" TEXT NOT NULL,
    "comment_id" INT NOT NULL REFERENCES "order_comment" ("id") ON DELETE CASCADE
);
-- downgrade --
ALTER TABLE "groups" DROP COLUMN "name";
DROP TABLE IF EXISTS "order_comment_image";
DROP TABLE IF EXISTS "order_comment";
