-- upgrade --
CREATE TABLE IF NOT EXISTS "courier_service" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "courier_service" varchar(256),
    "warehouse_id" VARCHAR(256),
    "city_id" INT NOT NULL REFERENCES "city" ("id") ON DELETE CASCADE,
    "partner_id" INT NOT NULL REFERENCES "partner" ("id") ON DELETE CASCADE
);
ALTER TABLE "item" ADD COLUMN IF NOT EXISTS "courier_service_code" VARCHAR(256);
-- downgrade --
DROP TABLE IF EXISTS "courier_service";
ALTER TABLE "table" DROP COLUMN IF EXISTS "courier_service_code"
