-- upgrade --
CREATE TABLE IF NOT EXISTS "profile_dispatcher" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "partner_id" INT NOT NULL REFERENCES "partner" ("id") ON DELETE CASCADE,
    "user_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);;
CREATE TABLE "profile_dispatcher_city" ("city_id" INT NOT NULL REFERENCES "city" ("id") ON DELETE CASCADE,"profile_dispatcher_id" INT NOT NULL REFERENCES "profile_dispatcher" ("id") ON DELETE CASCADE);
-- downgrade --
DROP TABLE IF EXISTS "profile_dispatcher_city";
DROP TABLE IF EXISTS "profile_dispatcher";
