-- upgrade --
DROP TABLE IF EXISTS "groups_user";
DROP TABLE IF EXISTS "groups" CASCADE;
DROP TABLE IF EXISTS "permissions" CASCADE;
DROP TABLE IF EXISTS "user_permissions";
DROP TABLE IF EXISTS "groups_permissions";
-- downgrade --
CREATE TABLE IF NOT EXISTS "permissions" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    "slug" VARCHAR(255) NOT NULL UNIQUE
);;
CREATE TABLE IF NOT EXISTS "groups" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL UNIQUE
);;
CREATE TABLE "groups_user" ("user_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,"groups_id" INT NOT NULL REFERENCES "groups" ("id") ON DELETE CASCADE);
CREATE TABLE "groups_permissions" ("groups_id" INT NOT NULL REFERENCES "groups" ("id") ON DELETE CASCADE,"permission_id" INT NOT NULL REFERENCES "permissions" ("id") ON DELETE CASCADE);
CREATE TABLE "user_permissions" ("user_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,"permission_id" INT NOT NULL REFERENCES "permissions" ("id") ON DELETE CASCADE);
