-- upgrade --
CREATE TABLE IF NOT EXISTS "complaint_reason" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "reason" VARCHAR(300),
    "score" SMALLINT NOT NULL  DEFAULT 0,
    "partner_id" INT NOT NULL REFERENCES "partner" ("id") ON DELETE CASCADE
);
-- downgrade --
DROP TABLE IF EXISTS "complaint_reason";
