-- upgrade --
CREATE TABLE IF NOT EXISTS "complaint" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "comment" TEXT,
    "status" VARCHAR(20) NOT NULL,
    "auto_created" BOOL NOT NULL  DEFAULT False,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "author_id" INT REFERENCES "user" ("id") ON DELETE SET NULL,
    "order_id" INT REFERENCES "order" ("id") ON DELETE SET NULL,
    "reason_id" INT NOT NULL REFERENCES "complaint_reason" ("id") ON DELETE CASCADE
);
COMMENT ON COLUMN "complaint"."status" IS 'NEW: new, REVIEWED: reviewed';
-- downgrade --
DROP TABLE IF EXISTS "complaint";
