-- upgrade --
CREATE TABLE IF NOT EXISTS "feedback_reason" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "reason" VARCHAR(300),
    "score" SMALLINT NOT NULL  DEFAULT 0,
    "partner_id" INT NOT NULL REFERENCES "partner" ("id") ON DELETE CASCADE
);;
CREATE TABLE IF NOT EXISTS "feedback" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "comment" TEXT,
    "final_score" SMALLINT NOT NULL  DEFAULT 0,
    "author_full_name" VARCHAR(120),
    "author_phone_number" VARCHAR(15),
    "author_role" VARCHAR(20) NOT NULL  DEFAULT 'system',
    "status" VARCHAR(20) NOT NULL  DEFAULT 'new',
    "auto_created" BOOL NOT NULL  DEFAULT False,
    "created_at" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "order_id" INT REFERENCES "order" ("id") ON DELETE SET NULL
);
COMMENT ON COLUMN "feedback"."author_role" IS 'RECEIVER: receiver, SYSTEM: system, MANAGER: manager';
COMMENT ON COLUMN "feedback"."status" IS 'NEW: new, REVIEWED: reviewed';;

DROP TABLE IF EXISTS "complaint";
DROP TABLE IF EXISTS "complaint_reason";
-- downgrade --
DROP TABLE IF EXISTS "feedback";
DROP TABLE IF EXISTS "feedback_reason";
