-- upgrade --
CREATE TABLE IF NOT EXISTS "profile_branch_manager" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "city_id" INT NOT NULL REFERENCES "city" ("id") ON DELETE CASCADE,
    "partner_id" INT NOT NULL REFERENCES "partner" ("id") ON DELETE CASCADE,
    "user_id" INT NOT NULL UNIQUE REFERENCES "user" ("id") ON DELETE CASCADE
);
-- downgrade --
DROP TABLE IF EXISTS "profile_branch_manager";
